import { Router } from 'express';
import dashboardRoutes from '../dashboard/dashboard.routes.js';
import activityLogRouter from '../dashboard/activityLog.routes.js';
import feedbackRouter from '../feedback/feedback.routes.js';
import licenseRoutes from '../licenses/license.routes.js';
import userRouter from '../user/routes.js';
import analyticsRouter from './analytics.routes.js';
import authRoutes from './auth/auth.routes.js';
import certificatesRouter from './certificates.routes.js';
import contractRouter from './contracts.routes.js';
import coursesRouter from './courses.js';
import enrollmentsRouter from './enrollments.js';
import exportRouter from './export.routes.js';
import generatorRouter from './generator/generator.routes.js';
import explorerRouter from './generator/explorer.routes.js';
import healthRouter from './health.routes.js';
import i18nRouter from './i18n.routes.js';
import osctRouter from './osct/osct.routes.js';
import playgroundRouter from './playground/playground.routes.js';
import simulatorRouter from './simulator/simulator.routes.js';
import learningRoutes from './learning/learning.routes.js';
import curriculumSearchRouter from './search/curriculum-search.routes.js';
import securityRouter from './security.routes.js';
import seoRouter from './seo.routes.js';
import studentsRouter from './students.js';
import simulatorErrorsRouter from './simulatorErrors.routes.js';
import termsOfServiceRouter from './termsOfService.routes.js';
import privacyPolicyRouter from './privacyPolicy.routes.js';
import playgroundValidateRouter from './playground.routes.js';
import oauthRouter from './oauth.routes.js';

import notificationRouter from '../notifications/notification.routes.js';
import notificationPreferencesRouter from '../notifications/preferences.routes.js';
import metricsRouter from './metrics.routes.js';
import dependenciesRouter from './dependencies.routes.js';
import infrastructureRouter from '../infrastructure/infrastructure.routes.js';
import simulatorIdeasRouter from '../simulator/simulator.routes.js';

import webhooksRouter from './webhooks.js';
import adminDLQRouter from './admin/dlq.routes.js';

const router: ReturnType<typeof Router> = Router();

router.use('/health', healthRouter);
router.use('/analytics', analyticsRouter);
router.use('/students', studentsRouter);
router.use('/certificates', certificatesRouter);
router.use('/courses', coursesRouter);
router.use('/enrollments', enrollmentsRouter);
router.use('/dashboard', dashboardRoutes);
router.use('/dashboard/activity-log', activityLogRouter);
router.use('/feedback', feedbackRouter);
router.use('/auth', authRoutes);
router.use('/learning', learningRoutes);
router.use('/search', curriculumSearchRouter);
router.use('/contracts', contractRouter);
router.use('/notifications', notificationRouter);
router.use('/notifications/preferences', notificationPreferencesRouter);
router.use('/security', securityRouter);
router.use('/licenses', licenseRoutes);
router.use('/seo', seoRouter);
router.use('/i18n', i18nRouter);
router.use('/generator', generatorRouter);
router.use('/generator', explorerRouter);
router.use('/osct', osctRouter);
router.use('/simulator', simulatorRouter);
router.use('/playground', playgroundRouter);
router.use('/export', exportRouter);
router.use('/webhooks', webhooksRouter);
router.use('/admin/dlq', adminDLQRouter);
router.use('/user', userRouter);
router.use('/metrics', metricsRouter);
router.use('/dependencies', dependenciesRouter);
router.use('/infrastructure', infrastructureRouter);
router.use('/simulator', simulatorIdeasRouter);
router.use('/simulator/errors', simulatorErrorsRouter);
router.use('/roadmap/tos', termsOfServiceRouter);
router.use('/playground', playgroundValidateRouter);
router.use('/playground/privacy-policy', privacyPolicyRouter);
router.use('/oauth', oauthRouter);

export default router;
