/**
 * TWAP oracle curve backtesting (Issue #1405).
 *
 * A spot-price oracle reports whatever the last trade says, which means a
 * single large, temporary trade — the classic flash-loan attack shape —
 * moves it instantly and fully. A time-weighted average price (TWAP) oracle
 * instead reports the average price over a trailing window, so a spike has
 * to survive for a large fraction of that window before it moves the
 * reported price by very much. This module builds a synthetic price
 * history, simulates a manipulation attack against it, computes both the
 * arithmetic-mean and geometric-mean TWAP curves, and measures exactly how
 * much attack resistance the averaging bought.
 *
 * Everything here is pure and deterministic given a seed, so it is testable
 * without a chart, a chain, or a random-number generator that can't be
 * pinned down.
 */

/** A small seeded PRNG (mulberry32) so "historical" price paths are reproducible. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export interface PriceSeriesOptions {
  /** Number of discrete "blocks" (ticks) to simulate. */
  length: number;
  startPrice: number;
  /** Per-tick volatility, as a fraction of price (e.g. 0.01 = ~1% per tick). */
  volatility: number;
  /** Deterministic seed — the same seed always produces the same path. */
  seed: number;
  /** Slow upward/downward bias per tick, as a fraction of price. Defaults to 0. */
  drift?: number;
}

/**
 * A synthetic "historical ledger" of spot prices, generated by a seeded
 * geometric random walk (log-normal steps, so prices stay positive).
 */
export function generatePriceSeries(options: PriceSeriesOptions): number[] {
  const { length, startPrice, volatility, seed, drift = 0 } = options;
  const rand = mulberry32(seed);
  const prices: number[] = [startPrice];

  for (let i = 1; i < length; i++) {
    // Box-Muller: turn two uniforms into one standard-normal sample.
    const u1 = Math.max(rand(), Number.EPSILON);
    const u2 = rand();
    const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
    const change = drift + volatility * z;
    const next = prices[i - 1] * Math.exp(change);
    prices.push(next);
  }

  return prices;
}

export interface ManipulationAttack {
  /** Tick index the attack begins at. */
  startIndex: number;
  /** How many ticks the manipulated price is held for (a flash loan unwinds within one tx/block in the extreme case). */
  durationTicks: number;
  /** Multiplier applied to price during the attack window, e.g. 3 = price triples. */
  magnitude: number;
}

/**
 * Overlay a manipulation attack onto a clean price series: for
 * `durationTicks` starting at `startIndex`, the spot price is multiplied by
 * `magnitude`, then the series returns to its unmanipulated path — modelling
 * a flash loan that pumps (or drains) a pool's spot price for the length of
 * one attacker-controlled transaction before unwinding.
 */
export function applyManipulationAttack(prices: number[], attack: ManipulationAttack): number[] {
  const { startIndex, durationTicks, magnitude } = attack;
  const attacked = [...prices];
  const end = Math.min(prices.length, startIndex + durationTicks);

  for (let i = Math.max(0, startIndex); i < end; i++) {
    attacked[i] = prices[i] * magnitude;
  }

  return attacked;
}

/** Rolling arithmetic-mean TWAP: the plain average price over the trailing window. */
export function computeArithmeticTwap(prices: number[], windowSize: number): number[] {
  if (windowSize < 1) throw new Error('windowSize must be at least 1');
  const out: number[] = [];
  let windowSum = 0;

  for (let i = 0; i < prices.length; i++) {
    windowSum += prices[i];
    if (i >= windowSize) windowSum -= prices[i - windowSize];
    const count = Math.min(i + 1, windowSize);
    out.push(windowSum / count);
  }

  return out;
}

/**
 * Rolling geometric-mean TWAP, computed via a rolling sum of logs (so it
 * stays O(n) instead of re-multiplying the whole window every tick, and
 * never overflows on a long series the way a running product would).
 */
export function computeGeometricTwap(prices: number[], windowSize: number): number[] {
  if (windowSize < 1) throw new Error('windowSize must be at least 1');
  const out: number[] = [];
  let logSum = 0;

  for (let i = 0; i < prices.length; i++) {
    logSum += Math.log(prices[i]);
    if (i >= windowSize) logSum -= Math.log(prices[i - windowSize]);
    const count = Math.min(i + 1, windowSize);
    out.push(Math.exp(logSum / count));
  }

  return out;
}

export interface DeviationStats {
  /** Largest absolute deviation of `series` from `baseline`, as a fraction (0.05 = 5%). */
  maxAbsDeviationPct: number;
  /** Index within `series` where that maximum occurred. */
  maxAbsDeviationIndex: number;
  /** Mean absolute deviation across the whole series, as a fraction. */
  meanAbsDeviationPct: number;
}

/** How far `series` (e.g. a TWAP curve) strays from `baseline` (e.g. the unmanipulated price), as a percentage. */
export function computeDeviation(baseline: number[], series: number[]): DeviationStats {
  if (baseline.length !== series.length) {
    throw new Error('baseline and series must be the same length');
  }
  if (baseline.length === 0) {
    return { maxAbsDeviationPct: 0, maxAbsDeviationIndex: -1, meanAbsDeviationPct: 0 };
  }

  let maxAbsDeviationPct = 0;
  let maxAbsDeviationIndex = 0;
  let sumAbsDeviationPct = 0;

  for (let i = 0; i < baseline.length; i++) {
    const base = baseline[i] || Number.EPSILON;
    const deviationPct = Math.abs(series[i] - base) / base;
    sumAbsDeviationPct += deviationPct;
    if (deviationPct > maxAbsDeviationPct) {
      maxAbsDeviationPct = deviationPct;
      maxAbsDeviationIndex = i;
    }
  }

  return {
    maxAbsDeviationPct,
    maxAbsDeviationIndex,
    meanAbsDeviationPct: sumAbsDeviationPct / baseline.length,
  };
}

export interface BacktestResult {
  clean: number[];
  spot: number[];
  arithmeticTwap: number[];
  geometricTwap: number[];
  /** How far the manipulated spot price strayed from the unmanipulated ("clean") price. */
  spotDeviation: DeviationStats;
  /** How far the arithmetic TWAP strayed from clean — this is the number that matters: how much the attack actually moved the oracle. */
  arithmeticTwapDeviation: DeviationStats;
  geometricTwapDeviation: DeviationStats;
  /** arithmeticTwapDeviation.max / spotDeviation.max — how much the averaging window damped the attack. Lower is better oracle resistance. 0 = fully absorbed, 1 = no protection at all. */
  resistanceRatio: number;
}

/**
 * Run a full backtest: generate a clean price path, overlay a manipulation
 * attack to get the observed spot price, compute both TWAP curves against
 * the manipulated spot feed (a TWAP oracle only ever sees spot prices — it
 * has no access to the counterfactual "clean" series), and measure how much
 * each curve deviates from the clean baseline.
 */
export function runTwapBacktest(
  seriesOptions: PriceSeriesOptions,
  attack: ManipulationAttack,
  windowSize: number,
): BacktestResult {
  const clean = generatePriceSeries(seriesOptions);
  const spot = applyManipulationAttack(clean, attack);
  const arithmeticTwap = computeArithmeticTwap(spot, windowSize);
  const geometricTwap = computeGeometricTwap(spot, windowSize);

  const spotDeviation = computeDeviation(clean, spot);
  const arithmeticTwapDeviation = computeDeviation(clean, arithmeticTwap);
  const geometricTwapDeviation = computeDeviation(clean, geometricTwap);

  const resistanceRatio =
    spotDeviation.maxAbsDeviationPct > 0
      ? arithmeticTwapDeviation.maxAbsDeviationPct / spotDeviation.maxAbsDeviationPct
      : 0;

  return {
    clean,
    spot,
    arithmeticTwap,
    geometricTwap,
    spotDeviation,
    arithmeticTwapDeviation,
    geometricTwapDeviation,
    resistanceRatio,
  };
}
